
# This CI will launch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 


name: CI with install

on:
  pull_request:    
    branches:
    - develop
    - main
 
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: conda init
        run: |
          conda init bash

      - name: install dependencies package
        run: |
          apt update -y
          apt-get install ffmpeg libsm6 libxext6  -y

      - name: create environment 1
        run: |
          conda env create -f environment_cad.yml
          conda activate env_cad

      - name: run script 1 of 3
        run: |
          python 1_creation_of_dagmc_geometry.py

      - name: create environment 1
        run: |
          conda env create -f environment_neutronics.yml
          conda activate env_neutronics

      - name: run script 2 of 3
        run: |
          2_run_openmc_dagmc_simulation.py

      - name: run script 3 of 3
        run: |
          3_extract_results.py
