
# This CI will launch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 


name: CI with install

on:
  pull_request:    
    branches:
    - develop
    - main
 
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install cadquery dependencies packages
        run: |
          apt update -y
          apt-get install ffmpeg libsm6 libxext6  -y

      - name: create environment 1 create geometry
        shell: bash
        run: |
          conda env create -f environment_cad.yml
          conda init bash
          source ~/.bashrc    
          conda activate env_cad
          python 1_creation_of_dagmc_geometry.py

      - name: create environment 2 run simulation
        shell: bash
        run: |
          conda env create -f environment_neutronics.yml
          conda init bash
          source ~/.bashrc   
          conda activate env_neutronics
          2_run_openmc_dagmc_simulation.py
          3_extract_results.py
